import cgfi

card = cgfi.Letter()

# The character 'Í' is newline and character '®' is a
# forward slash in Animal Crossing
card.contents = 'Hello, !                This is a test messageÍ' + \
                'generated by @Faschz\'s CustomÍ' + \
                'Card Generator which is found here: github.com®Faschz®cgfiÍÍ' + \
                'Enjoy the gift!'
card.name_position = 7
card.item_id = 0x5828

card.create_dec("Example.dec")

cgfi.convert_dec_to_vpk("Example.dec", "Example.vpk")
cgfi.convert_vpk_to_bin("ac.header", "gba.vpk", "Example.vpk", "Example.bin")
